# Generated by Django 3.2.19 on 2024-02-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter your Name', max_length=100)),
                ('email', models.EmailField(help_text='Enter Email', max_length=100)),
                ('mobile', models.CharField(help_text='Enter Mobile Number', max_length=20)),
                ('message', models.CharField(help_text='Enter Your Message', max_length=100)),
            ],
            options={
                'db_table': 'contact_details',
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter Username', max_length=100)),
                ('email', models.EmailField(help_text='Enter Email', max_length=100)),
                ('mobile', models.CharField(help_text='Enter Mobile Number', max_length=20)),
                ('address', models.TextField(help_text='Enter Address', max_length=300)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'user_reg_details',
            },
        ),
    ]
